version: '3.8'

services:

  test_app:
    container_name: test_app
    build:
      context: .
      dockerfile: Dockerfile
    command: "pytest -vv"
    environment:
      - DATABASE_URL=postgresql://user_db:password_db@db/name_db
    networks:
      - test_network

networks:
  test_network:
    external:
      name: app_network