version: '3.8'

services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      bash -c "
        echo 'Starting project...' &&
        while !</dev/tcp/db/5432; do sleep 1; done &&
        uvicorn src.main:app --reload --workers 1 --host 0.0.0.0
      "
    volumes:
      - ./src/:/app/src/
    environment:
      - DATABASE_URL=postgresql://user_db:password_db@db/name_db
    networks:
      - app_network
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_db
      - POSTGRES_PASSWORD=password_db
      - POSTGRES_DB=name_db
    networks:
      - app_network
    expose:
      - 5432

volumes:
  postgres_data:

networks:
  app_network:
    name: app_network

### Вместо 'depends_on:' использую в 'entrypoint:' (или command:) проверку
### while !</dev/tcp/db/5432; do sleep 1; done
