version: '3.8'

services:

  test_app:
    container_name: test_app
    build: ./src
    command: "pytest -vv"
    environment:
      - DATABASE_URL=postgresql://user_db:password_db@db/name_db
#    networks:
#      - app_network
#
#networks:
#  app_network:
#    name: app_network